version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pip
    versions:
    - "21.0"
    - 21.0.1
  - dependency-name: coverage
    versions:
    - "5.4"
  - dependency-name: pyyaml
    versions:
    - "5.1"
